#???
server:
  port: 8089
  # Servlet?Java?????????????
  servlet:
    # ????
    encoding:
      # ?????????
      force: true
      # ???
      charset: UTF-8

youbili:
  jwt:
    # JWT????????????
    duration-in-minute: 86400L
    # JWT?secretKey
    secret-key: fNesMDkqrJFdsfDSwAbFLJ8SnsHJ438AF72D73aKJSmfdsafdLKKAFKDSJ


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/youbili_v1?
    username: root
    password: root
    druid:
      max-active: 200
      initial-size: 5
    type: com.alibaba.druid.pool.DruidDataSource







  #Redis??
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      username: ~
      password: ~
  jackson:
    default-property-inclusion: non_null



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/**/*.xml


logging:
  level:
    security.jwt: debug

