package security.jwt.securityjwt;

import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn

@Slf4j
@SpringBootApplication
public class SecurityJwt {

    public static void main(String[] args) {
        SpringApplication.run(SecurityJwt.class, args);
        log.info("---------------项目启动成功---------------");
    }

}
